application: albatros-kevinlot-me
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /dist
  static_dir: web/dist

- url: /bower_components
  static_dir: web/bower_components

- url: /robots.txt
  script: web/robots.txt

- url: /.*
  script: web/index.html
