application: albatros-kevinlot-me
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /app/(.*)
  static_files: app/\1
  upload: app/.*

- url: /bower_components/(.*)
  static_files: bower_components/\1
  upload: bower_components/.*

- url: /dist/(.*)
  static_files: dist/\1
  upload: dist/.*

- url: /icons/(.*)
  static_files: icons/\1
  upload: icons/.*

- url: /img/(.*)
  static_files: img/\1
  upload: img/.*

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  script: index.html