application: albatros-kevinlot-me
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /css/(.*)
  static_files: css/\1
  upload: css/.*

- url: /fonts/(.*)
  static_files: fonts/\1
  upload: fonts/.*

- url: /icons/(.*)
  static_files: icons/\1
  upload: icons/.*

- url: /img/(.*)
  static_files: img/\1
  upload: img/.*

- url: /js/(.*)
  static_files: js/\1
  upload: js/.*

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  script: index.html