application: albatros-kevinlot-me
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: web/index.html

- url: /dist
  static_dir: web/dist

- url: /robots.txt
  script: web/robots.txt

- url: /
  script: index.html