name: test_workflow

env:
    CI: 1
    IS_CI: 1

on:
    push:
        branches:
            - master
            - main
            - "**"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install packages
              run: yarn install --frozen-lockfile

            - name: Check format
              run: yarn format
            - name: Linters
              run: yarn lint
